'use client'

import { useState, useEffect } from 'react'
import { CheckCircle, XCircle, Clock, Download, RotateCcw, AlertTriangle } from 'lucide-react'

interface SessionResultsProps {
  sessionId: string
  endReason: 'completed' | 'violation' | 'timeout'
  onRestart: () => void
}

export default function SessionResults({ sessionId, endReason, onRestart }: SessionResultsProps) {
  const [sessionData, setSessionData] = useState<any>(null)
  const [messages, setMessages] = useState<any[]>([])
  const [isLoading, setIsLoading] = useState(true)

  useEffect(() => {
    fetchSessionData()
  }, [sessionId])

  const fetchSessionData = async () => {
    try {
      // Get session data
      const sessionResponse = await fetch(`/api/session?sessionId=${sessionId}`)
      const sessionResult = await sessionResponse.json()
      
      // Get chat messages
      const chatResponse = await fetch(`/api/chat?sessionId=${sessionId}`)
      const chatResult = await chatResponse.json()
      
      setSessionData(sessionResult.sessionData)
      setMessages(chatResult.messages || [])
    } catch (error) {
      console.error('Failed to fetch session data:', error)
    } finally {
      setIsLoading(false)
    }
  }

  const getEndReasonDetails = () => {
    switch (endReason) {
      case 'completed':
        return {
          icon: <CheckCircle className="w-16 h-16 text-green-600" />,
          title: 'Interview Completed!',
          message: 'Congratulations! You have successfully completed the AI interview session.',
          bgColor: 'bg-green-50',
          borderColor: 'border-green-200'
        }
      case 'timeout':
        return {
          icon: <Clock className="w-16 h-16 text-blue-600" />,
          title: 'Time Limit Reached',
          message: 'Your 30-minute interview session has ended. Thank you for your time.',
          bgColor: 'bg-blue-50',
          borderColor: 'border-blue-200'
        }
      case 'violation':
        return {
          icon: <XCircle className="w-16 h-16 text-red-600" />,
          title: 'Session Terminated',
          message: 'The interview was ended due to rule violations. Please review the guidelines for next time.',
          bgColor: 'bg-red-50',
          borderColor: 'border-red-200'
        }
    }
  }

  const downloadTranscript = () => {
    const transcript = messages
      .filter(msg => msg.type === 'ai' || msg.type === 'user')
      .map(msg => {
        const timestamp = new Date(msg.timestamp).toLocaleTimeString()
        const sender = msg.type === 'ai' ? 'PrepStart AI' : 'Candidate'
        return `[${timestamp}] ${sender}: ${msg.message}`
      })
      .join('\n\n')

    const fullTranscript = `
PrepStart AI Interview Transcript
================================

Session ID: ${sessionId}
Date: ${new Date().toLocaleDateString()}
End Reason: ${endReason.charAt(0).toUpperCase() + endReason.slice(1)}

${sessionData ? `
Candidate: ${sessionData.candidateData?.name || 'N/A'}
Position: ${sessionData.jobData?.role_name || 'N/A'}
` : ''}

Interview Transcript:
${transcript}

---
Generated by PrepStart AI Interview Platform
    `.trim()

    const blob = new Blob([fullTranscript], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `interview-transcript-${sessionId}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const details = getEndReasonDetails()

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50 flex items-center justify-center">
        <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-md w-full text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading session results...</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-4xl w-full p-8">
        {/* Header */}
        <div className={`${details.bgColor} ${details.borderColor} border rounded-2xl p-8 mb-8 text-center`}>
          <div className="flex justify-center mb-4">
            {details.icon}
          </div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">{details.title}</h1>
          <p className="text-gray-700 text-lg">{details.message}</p>
        </div>

        {/* Session Summary */}
        {sessionData && (
          <div className="grid md:grid-cols-2 gap-8 mb-8">
            <div className="bg-gray-50 rounded-xl p-6">
              <h3 className="font-semibold text-gray-900 mb-4">Session Details</h3>
              <div className="space-y-3">
                <div className="flex justify-between">
                  <span className="text-gray-600">Candidate:</span>
                  <span className="font-medium">{sessionData.candidateData?.name || 'N/A'}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Position:</span>
                  <span className="font-medium">{sessionData.jobData?.role_name || 'N/A'}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Session ID:</span>
                  <span className="font-mono text-sm">{sessionId}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">End Reason:</span>
                  <span className="font-medium capitalize">{endReason}</span>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 rounded-xl p-6">
              <h3 className="font-semibold text-gray-900 mb-4">Interview Stats</h3>
              <div className="space-y-3">
                <div className="flex justify-between">
                  <span className="text-gray-600">Messages Exchanged:</span>
                  <span className="font-medium">{messages.length}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Questions Asked:</span>
                  <span className="font-medium">{messages.filter(m => m.type === 'ai').length}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Responses Given:</span>
                  <span className="font-medium">{messages.filter(m => m.type === 'user').length}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Duration:</span>
                  <span className="font-medium">
                    {messages.length > 0 
                      ? Math.round((messages[messages.length - 1].timestamp - messages[0].timestamp) / 1000 / 60) + ' minutes'
                      : 'N/A'
                    }
                  </span>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Conversation Preview */}
        {messages.length > 0 && (
          <div className="mb-8">
            <h3 className="font-semibold text-gray-900 mb-4">Conversation Preview</h3>
            <div className="bg-gray-50 rounded-xl p-6 max-h-64 overflow-y-auto">
              <div className="space-y-4">
                {messages.slice(0, 6).map((message, index) => (
                  <div key={index} className={`flex ${message.type === 'user' ? 'justify-end' : 'justify-start'}`}>
                    <div className={`max-w-xs px-4 py-2 rounded-lg ${
                      message.type === 'user'
                        ? 'bg-blue-600 text-white'
                        : 'bg-white border text-gray-900'
                    }`}>
                      <p className="text-sm">{message.message}</p>
                      <p className={`text-xs mt-1 ${
                        message.type === 'user' ? 'text-blue-200' : 'text-gray-500'
                      }`}>
                        {new Date(message.timestamp).toLocaleTimeString()}
                      </p>
                    </div>
                  </div>
                ))}
                {messages.length > 6 && (
                  <div className="text-center text-gray-500 text-sm">
                    ... and {messages.length - 6} more messages
                  </div>
                )}
              </div>
            </div>
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex gap-4">
          <button
            onClick={downloadTranscript}
            className="flex items-center space-x-2 px-6 py-3 border border-gray-300 rounded-xl font-medium text-gray-700 hover:bg-gray-50 transition-colors"
          >
            <Download className="w-5 h-5" />
            <span>Download Transcript</span>
          </button>

          <button
            onClick={onRestart}
            className="flex-1 flex items-center justify-center space-x-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white py-3 px-6 rounded-xl font-semibold hover:from-blue-700 hover:to-purple-700 transition-all"
          >
            <RotateCcw className="w-5 h-5" />
            <span>Start New Interview</span>
          </button>
        </div>

        {/* Feedback Section */}
        {endReason === 'violation' && (
          <div className="mt-8 p-6 bg-yellow-50 border border-yellow-200 rounded-xl">
            <div className="flex items-start space-x-3">
              <AlertTriangle className="w-6 h-6 text-yellow-600 mt-1" />
              <div>
                <h4 className="font-semibold text-yellow-800 mb-2">Tips for Next Time</h4>
                <ul className="text-yellow-700 text-sm space-y-1">
                  <li>• Keep your camera and microphone enabled throughout the interview</li>
                  <li>• Avoid switching tabs or minimizing the browser window</li>
                  <li>• Ensure stable internet connection</li>
                  <li>• Find a quiet, distraction-free environment</li>
                </ul>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
